### ISSUE TITLE
meeting 04.27

### ISSUE THREAD

**Issue by thin-lizard** [PugetSoundClinic-PIT/Fare-Fair#11]
- talk through 2nd IRR test - mostly in agreement over inclusion (clarifying Q about naming specific), disagreement over methods  
    - exclude micromobility
    -  Include No. 29 (https://www.webofscience.com/wos/woscc/full-record/WOS:000576834400002) when tncs are active in a location it affect choices about ridership / mobility  
- solidify screening protocol and criteria
- next week: discuss variables to extract

**Comment by thin-lizard** [comment]
For next week:
- @samMint + @lindseysschwartz  will run each query in W0S and take a sample of <25 papers following the protocol nic laid out (https://github.com/PugetSoundClinic-PIT/Fare-Fair/blob/main/protocol-process.md) -- determine if using the tool worth the overhead or if we should just use Google sheets 
    - LS will test DNC; SM will test TNC 
- Once we confirm tool vs spreadsheet, we will run queries against the 3 databases - W0S, IEEE, ACM - and test out PubMed. For each search, record: 
    1. the query used (TNC or DNC)
    2. the database searched
    3.  the initial number of results 
    4. and the number of papers left after we remove duplicates 
- Before we screen, we will divvy up the sample
- We'll discuss variables to extract in our next meeting - to prepare, we'll each review our RQs to make sure that we're extracting the info we'll need

**Comment by thin-lizard** [comment]
- SM and LS talk about ASR review and workflow - maybe discuss examples of 'UX-ish' studies if time
- Discuss variables to extract

**Comment by lindseysschwartz** [comment]
test pubmed and see how many duplicates / false positives
