### ISSUE TITLE
05.04 meeting - to-dos for next week

### ISSUE THREAD

**Issue by thin-lizard** [PugetSoundClinic-PIT/Fare-Fair#13]
- For next we will execute queries, aggregate datasets, and start screening
    - Instructions for running queries and exporting results are on p. 6 [of the protocol](https://docs.google.com/document/d/1Joo48erBNGUfORNYEhUMlmrmWQltL2xmhEgxtFEIlQg/edit#) 
        - @samMint => TNC query
        - @lindseysschwartz => DNC query + checking out PubMed and see about duplicates / false positives
    - Datasets from each database (separate for now) are linked out [in the wiki](https://github.com/PugetSoundClinic-PIT/Fare-Fair/wiki/Datasets) - @nniiicc will aggregate and de-duplicate
    - When we have the 'comprehensive' TNC and DNC datasets, we'll divvy each by 3 (so each of us screens a portion of TNC and DNC studies)
- We will each spend 4 hours screening and check in about how far we get
- After we gauge timeline for screening...we will run a test for data extraction

**Comment by thin-lizard** [comment]
Update: PubMed returned 14 results for the DNC query, only 1 seems potentially relevant [see results here](https://pubmed.ncbi.nlm.nih.gov/?term=%22delivery%20network%20company%22%5BTitle%2FAbstract%5D%20OR%20%22third-party%20delivery%22%5BTitle%2FAbstract%5D%20OR%20%22food%20delivery%20network%20company%22%5BTitle%2FAbstract%5D%20OR%20%22food%20delivery%20platform%22%5BTitle%2FAbstract%5D%20OR%20%22food%20delivery%22%5BTitle%2FAbstract%5D%20OR%20%22grocery%20delivery%20platform%22%5BTitle%2FAbstract%5D%20OR%20%22grocery%20delivery%22%5BTitle%2FAbstract%5D%20OR%20%22Instacart%22%5BTitle%2FAbstract%5D%20OR%20%22Uber%20Eats%22%5BTitle%2FAbstract%5D%20OR%20%22DoorDash%22%5BTitle%2FAbstract%5D%20OR%20%22Gojek%22%5BTitle%2FAbstract%5D%20OR%20%22Shipt%22%5BTitle%2FAbstract%5D%20OR%20%22Roadie%22%5BTitle%2FAbstract%5D%20OR%20%22Jumia%20Food%22%5BTitle%2FAbstract%5D%20OR%20%22Deliveroo%22%5BTitle%2FAbstract%5D%20OR%20%22Foodora%22%5BTitle%2FAbstract%5D%20OR%20%22Swiggy%22%5BTitle%2FAbstract%5D%20OR%20%22PedidosYa%22%5BTitle%2FAbstract%5D%20OR%20%22Rappi%22%5BTitle%2FAbstract%5D%20OR%20%22GoPuff%22%5BTitle%2FAbstract%5D%20OR%20%22Postmates%22%5BTitle%2FAbstract%5D%20OR%20%22JustEat%22%5BTitle%2FAbstract%5D%20OR%20%22Saucey%22%5BTitle%2FAbstract%5D%20OR%20%22Grubhub%22%5BTitle%2FAbstract%5D%20OR%20%22Zomato%22%5BTitle%2FAbstract%5D%20OR%20%22Glovo%22%5BTitle%2FAbstract%5D%20OR%20%22Careem%22%5BTitle%2FAbstract%5D%20OR%20%22Meituan%22%5BTitle%2FAbstract%5D%20OR%20%22Ele.me%22%5BTitle%2FAbstract%5D%20OR%20%22Amazon%20Flex%22%5BTitle%2FAbstract%5D%20OR%20%22Amazon%20Fresh%22%5BTitle%2FAbstract%5D%20OR&filter=pubt.booksdocs&filter=pubt.clinicaltrial&filter=pubt.meta-analysis&filter=pubt.randomizedcontrolledtrial&filter=dates.2011-2023) -- and 11 results for the TNC query with 1 or 2 potentially relevant [see results here](https://pubmed.ncbi.nlm.nih.gov/?term=%22transportation+network+company%22%5BTitle%2FAbstract%5D+OR+%22ridehail+platform%22%5BTitle%2FAbstract%5D+OR+%22rideshare+platform%22%5BTitle%2FAbstract%5D+OR+%22ride-hail+platform%22%5BTitle%2FAbstract%5D+OR+%22ride-hail%22%5BTitle%2FAbstract%5D+OR+%22ridehail%22%5BTitle%2FAbstract%5D+OR+%22rideshare%22%5BTitle%2FAbstract%5D+OR+%22Lyft%22%5BTitle%2FAbstract%5D+OR+%22Uber%22%5BTitle%2FAbstract%5D+OR+%22Wingz%22%5BTitle%2FAbstract%5D+OR+%22HopSkipDrive%22%5BTitle%2FAbstract%5D+OR+%22Cabify%22%5BTitle%2FAbstract%5D+OR+%22Ziro%22%5BTitle%2FAbstract%5D+OR+%22Gojek%22%5BTitle%2FAbstract%5D+OR+%22Careem%22%5BTitle%2FAbstract%5D+OR+%22DiDi%22%5BTitle%2FAbstract%5D+OR+%22Little+Cab%22%5BTitle%2FAbstract%5D&sort=&filter=pubt.booksdocs&filter=pubt.clinicaltrial&filter=pubt.meta-analysis&filter=pubt.randomizedcontrolledtrial&filter=dates.2011-2023&filter=pubt.booksdocs&filter=pubt.clinicaltrial&filter=pubt.meta-analysis&filter=pubt.randomizedcontrolledtrial&filter=dates.2011-2023)

**Comment by samMint** [comment]
TNC

- [WOS - 1,813 results](https://docs.google.com/spreadsheets/d/1RuieBjvlMY-D7SubVqdbVxJ0liCevHWpaoYHsC_f8TQ/edit#gid=1122416013)

- [IEEE - 773 results](https://docs.google.com/spreadsheets/d/1aHQNMnw0K-qJUPT7N58lmnt4lC4bx57YWwog6DitzZo/edit#gid=1674987390)

- [ACM - 180 results](https://docs.google.com/spreadsheets/d/1ChPPRrWZ2Bp20bFvuYbRxdT3i1T0CS7LNPkKE-ghZqQ/edit#gid=1721434637)
