### ISSUE TITLE
Documenting test queries in web of science

### ISSUE THREAD

**Issue by lindseysschwartz** [PugetSoundClinic-PIT/Fare-Fair#5]

**Comment by lindseysschwartz** [comment]
**"Amazon Flex" + driver**

1 result: https://www.webofscience.com/wos/woscc/summary/b8173632-ce3c-4f57-b2ea-6d04c24db605-80bff1a3/relevance/1

**Comment by lindseysschwartz** [comment]
**Uber + driver**

386 results: https://www.webofscience.com/wos/woscc/summary/58235fbc-9a27-4cd1-91ce-98e124625a3d-80c049f4/relevance/1 
- familar friends Hall & Krueger, Roseblat & Stark, Chen (the Uber economist), Katie Wells
- studies on the mental health of drivers..."technostress"; the taxi industry
- case studies in specific countries: Poland, Taiwan, Australia, Brazil, India, Canada -- this seems like a good sign

**Comment by lindseysschwartz** [comment]
**DoorDash + restaurant**

2 results: https://www.webofscience.com/wos/woscc/summary/39b3f3d7-6091-4eab-9150-1f6918436be0-80c10ada/relevance/1
- I expected a small number of results - there may be a better approach for collecting publications that aren't about TNCs

**Comment by lindseysschwartz** [comment]
`"delivery network company" OR "third-party delivery" OR "DoorDash" OR "Gojek" OR "Shipt" OR "Caviar" OR "Roadie" OR "Jumia Food" OR "Deliveroo" OR "Foodora" OR "Swiggy" OR "PedidosYa" OR "Rappi"`

- 1286 results
- `Caviar` returns studies about caviar the food (273 results are in Marine Biology, and more scattered across Dairy & Animal Sciences, genome sciences, molecular biology, and other physical sciences)
- Eliminating `Caviar` as a search term yields 85 results - a mix of studies about delivery logistics, economic sustainability of the delivery sector, labor protests
- `Shipt` and `Rappi` returned a few non-relevant studies

**Comment by nniiicc** [comment]
Next steps:

Decide on a set of queries that includes 
 - Modified (e.g. `ridehail`) 
 - Add companies or platforms from LS list of most prevalent 
 - Keep DNC vs TNC datasets separately
