### ISSUE TITLE
04.20 - to do 

### ISSUE THREAD

**Issue by thin-lizard** [PugetSoundClinic-PIT/Fare-Fair#9]
- [x] solidify queries
- [x] talk through IRR and screening criteria

By 04.27:
-  solidify screening criteria 
-  solidify variables to extract 

- For next meeting: we do a 2nd IRR test - 15 TNC and 15 DNC - for inclusion / exlcusion and qual/quant/mixed/engineering
    - in next meeting we talk through screening protocol, criteria, and variables to extract 
    - @samMint will document our meeting today (04.20)

**Comment by samMint** [comment]
Hey Lindsey - dropping our 4.20 summary notes here for now. Not sure if I can add pages to the wiki. (feel free to change anything/everything that I might have missed or misremembered!) 

4.20
We began by finalizing our queries. We decided that the queries we used for the initial IRR test were satisfactory—they captured a wide range of relevant publications, including all but 1 of the key papers we identified prior to query testing.

Next we discussed inclusion and exclusion criteria. We clarified our broad inclusion need: a study must make a claim about a gig economy company. Studies that make claims about other domains should be excluded from our study, even when some aspect of the gig economy is discussed in the study's abstract (e.g. the first item in our IRR sample).

We evaluated our IRR sample and discussed discrepancies in inclusion/exclusion decisions. We established a better collective sense for why a paper should or shouldn't be included, though we aim to further refine our screening process and criteria by our next meeting, prior to which an additional 15 papers for each query will be independently evaluated. In this new IRR test we will include an appraisals of methodology (not sure if best word) column for each paper. We ended the meeting by documenting criteria for four methodologies we expect to find in our sample: quantitative, qualitative, mixed, and engineering.
